//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsCart
    {
        public int ID { get; set; }
        public int CartID { get; set; }
        public int ProductID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Products Products { get; set; }
    }
}
